name: Deploy App to Production

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["6.0.x"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Publish
        run: dotnet publish -c Release --os linux -o deploy
      - name: Copy files to prod server via ssh
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /home/runner/work/Flight-Simulator-API/Flight-Simulator-API/deploy/
          remote: ${{ secrets.REMOTE_TARGET }}
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.REMOTE_SSH_KEY }}
      - name: Set appsettings.json to server
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          command: echo -e ${{ secrets.APP_SETTINGS_FILE }} > ${{ secrets.REMOTE_TARGET }}/appsettings.json
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.REMOTE_SSH_KEY }}
      - name: Restart server
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          command: sudo systemctl restart fsapi
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.REMOTE_SSH_KEY }}
